### ISSUE TITLE
Postcodes only go up to S

### ISSUE THREAD

**Issue by aembleton** [pezholio/UK-Postcodes#10]
Postcodes in postcodes.sql.gz only go up to S, they don't include anything beginning with W for example.

**Comment by EnvolveTech1** [comment]
Any idea when this might be addressed? As it stands, it's unusable without the full set of postcodes.

**Comment by pezholio** [comment]
Unfortunately, I can't push the full databse due to Github's size restrictions. You may want to look at the (still in development) [next generation version of UK Postcodes](http://github.com/theodi/uk-postcodes), which has setup scripts to import the relevant data.
