### ISSUE TITLE
Output is invalid due to geohash.org 403 Forbidden response

### ISSUE THREAD

**Issue by walkermatt** [pezholio/UK-Postcodes#11]
Currently the output from http://www.uk-postcodes.com/ contains a chunk of html returned in response to the geohash.org call to obtain a geohash for the given location. This affect all formats except RDF.

The html returned is:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /
on this server.</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

Assuming that an appropriate HTTP status code is returned then it could be checked and the geohash omitted if 200 is not returned?

```
 $geohash_status = curl_getinfo($ch_geohash, CURLINFO_HTTP_CODE);
```

**Comment by pezholio** [comment]
I've just pushed a fix for this :+1:
