### ISSUE TITLE
Unknown Postcodes don't respect API format of the call

### ISSUE THREAD

**Issue by alastairandrew** [pezholio/UK-Postcodes#12]
I've been calling the UK-postcodes API from within an R script. For most postcodes this works brilliantly; I make a JSON request and get a largely JSON response. There are minor issues surrounding the broken geohashing but they've already been raised.

However, in the situation when the postcode is not found (such as AB39 2FT) then what's returned is always the HTML of the not found page. It would be more elegant if the failed search was indicated in the same format as the request.

**Comment by pezholio** [comment]
Good shout. All my work is now going into the [next generation version of UK Postcodes](http://github.com/theodi/uk-postcodes), so I don't think I'll have time to fix this. However, the new version should be going live pretty soon, or you could follow the instructions and set up a local instance.

**Comment by pezholio** [comment]
I will, however, raise this as an issue on the new version, as I think this is a feature that I haven't yet built in
