### ISSUE TITLE
522 error / site down

### ISSUE THREAD

**Issue by mttsmmrssprks** [pezholio/UK-Postcodes#13]
Hi @pezholio 
Any chance https://www.uk-postcodes.com will be live again soon? I've visited a few times over the past few weeks and keep getting a 522 error.
Thank you.

![image](https://user-images.githubusercontent.com/5499606/47003207-a448d880-d126-11e8-94ce-e98cbc5518ed.png)

**Comment by pezholio** [comment]
It's dead I'm afraid. Hosting was getting expensive, and it was pretty unstable, and I didn't have a lot of time to support on top of a full time job, kids etc. There's far better solutions out there these days too. https://postcodes.io/ worth a look 👍
