### ISSUE TITLE
Error on MySQL import of postcodes.sql

### ISSUE THREAD

**Issue by RickSeymour** [pezholio/UK-Postcodes#2]
ERROR 1064 (42000) at line 1881768

This is caused by an incorrect closing of the MySQL Insert command

**Comment by ivebeenlinuxed** [comment]
Please download http://www.uk-postcodes.com/data.sql

**Comment by ivebeenlinuxed** [comment]
(Or compressed version http://www.uk-postcodes.com/data.sql.lzma)
