### ISSUE TITLE
Spaces in postcode

### ISSUE THREAD

**Issue by RickSeymour** [pezholio/UK-Postcodes#3]
Example - "S2  4SS" contains a double space. This makes matching difficult.

Recommend ensure uppercase and no whitespace.

This would allow matching and if required "prettify" the postcode. (By adding in a desired space)

**Comment by ivebeenlinuxed** [comment]
This is the standard Codepoint format, designed to ensure postcodes remain a fixed length. Can you explain the issue you have with "Matching" further?

I suggest you use the following regex from my boiler framework (@ivebeenlinuxed/Boiler) for any standard postcode matching:

preg_match("/\A(\w{1,2}\d{1,2}\w?){1}(?<sp>\s{0,3})?(\d\w{2}){1}$/", $pcode, $m)

This should match any postcode (great for scraping too!)

P.S. Some postcodes will contain three spaces in the middle!
