### ISSUE TITLE
London Postcodes

### ISSUE THREAD

**Issue by Surefyre** [pezholio/UK-Postcodes#6]
Can't find many London postcodes in the MySQL export, e.g. SW15, WC1a, outcodes

Cheers

EDIT: MySQL reports error at line 1881768 (almost the end of the dump file) which is presumably caused by the SQL export tool you're using - perhaps mysqldump would be better?

('S21 5RA',0,53.303741,-1.388106,440873,378707,'E10000007','','E07000038','E05003436','E14000843',''),
    ('S21 5RB',0,53.308968,-1.388692,440829,379288,'E10000007','','E07000038','E05003436','E14000843',''),
    ('S21 5RD',0,53.301727,-1.396943,440286,378478,'E10000007','','E07000038','E05003436','E14000843',''),
    (; <<<--------------------- THIS - is line 1883516 of the text in MySQL Workbench

/*!40000 ALTER TABLE `postcodes` ENABLE KEYS */;
UNLOCK TABLES;

**Comment by ivebeenlinuxed** [comment]
Hi,

I will try and release the PHP Codepoint Import tool...

Will

**Comment by ivebeenlinuxed** [comment]
Please download http://www.uk-postcodes.com/data.sql
